### ISSUE TITLE
missing dependency 

### ISSUE THREAD

**Issue by radkoradko** [avilab/vs#1]
Missing dependency in environment.yml

Traceback (most recent call last):
  File "/gpfs/hpchome/radko/vs/src/.snakemake.vnp37zlc.sequence_cleaner.py", line 8, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
[Wed Mar 28 16:02:38 2018] Error in rule tantan_goodreads:
[Wed Mar 28 16:02:38 2018]     jobid: 0
[Wed Mar 28 16:02:38 2018]     output: output/tantan_goodreads/I1164_12629_Harvard_SIV_196_06_2_24_12_mini.tantan.goodseq.fa

**Comment by tpall** [comment]
fixed by cf707a953d9b7cb81bcf436dd2ec663b77eac887
